#!/bin/sh
# armdeck: dbus-send adapter in the Steam container (/usr/local/bin/dbus-send).
# Steam suspends/powers off/reboots with "dbus-send --system ... login1.Manager.Suspend boolean:true".
# logind refuses a plain Suspend while inhibitors exist (on postmarketOS every SSH session holds
# "inhibit=sleep"): BlockedByInhibitorLock, and Steam is left with a black screen. Here Suspend,
# PowerOff and Reboot become ...WithFlags with SD_LOGIND_SKIP_INHIBITORS (16); polkit allows
# that for the user gabriel. Every other call passes through unchanged. Log: ~/op8-dbus-send.log
REAL=/usr/bin/dbus-send
L="$HOME/op8-dbus-send.log"
case " $* " in
	*" org.freedesktop.login1.Manager.Suspend "*|*" org.freedesktop.login1.Manager.PowerOff "*|*" org.freedesktop.login1.Manager.Reboot "*)
		echo "$(date '+%F %T') received: $*" >> "$L"
		for a do
			shift
			case "$a" in
				org.freedesktop.login1.Manager.Suspend|org.freedesktop.login1.Manager.PowerOff|org.freedesktop.login1.Manager.Reboot)
					a="${a}WithFlags" ;;
				boolean:true|boolean:false)
					a="uint64:16" ;;
			esac
			set -- "$@" "$a"
		done
		echo "$(date '+%F %T') sent: $*" >> "$L"
		"$REAL" "$@" >> "$L" 2>&1
		rc=$?
		echo "$(date '+%F %T') exit code: $rc" >> "$L"
		exit $rc
		;;
esac
exec "$REAL" "$@"
