#!/bin/sh
# steamed-noodle: /usr/bin/steamos-polkit-helpers/steamos-priv-write in containerul Steam.
# Steam scrie luminozitatea prin acest helper ("steamos-priv-write <cale> <valoare>"). Permite
# doar luminozitatea ecranului; fisierul e scriibil de grupul video pe gazda (regula udev
# 72-steamed-noodle-backlight.rules), iar userul gabriel e in video.
case "$1" in
	/sys/class/backlight/*/brightness) ;;
	*) echo "steamos-priv-write: cale nepermisa: $1" >&2; exit 1 ;;
esac
case "$2" in
	''|*[!0-9]*) echo "steamos-priv-write: valoare invalida: $2" >&2; exit 1 ;;
esac
printf '%s' "$2" > "$1"
