#!/bin/bash
# deploy.sh (armdeck): keeps the phone in step with userspace/ in this repository, following
# userspace/deploy-manifest.txt. Run on the PC (Git Bash or Linux).
#   tools/deploy.sh          check: each manifest entry as same, DIFFERENT, missing or root-only
#   tools/deploy.sh stage    copies the entries that are not "same" to ~/armdeck-staging/deploy/
#                            on the phone, with an install.sh; nothing is installed yet
# Then on the phone (it asks for the sudo password):
#   sh ~/armdeck-staging/deploy/install.sh
# install.sh backs up every file it replaces under ~/armdeck-staging/deploy/backup-<time>/,
# installs the new copies, moves files with an old name out of the way, reloads systemd and udev
# and restarts the small services whose files changed. The Steam session and the audio services
# pick up their files when they next start (it says which). Files are compared without CR, since
# git may check them out with CRLF on Windows; the copies sent to the phone have LF only.
set -uo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
U=$ROOT/userspace
MANIFEST=$U/deploy-manifest.txt
# the phone: $OP8_PHONE, else the first line of tools/.phone (local, not committed), else the
# postmarketOS address over the USB cable
PHONE=${OP8_PHONE:-$(head -1 "$ROOT/tools/.phone" 2>/dev/null)}
PHONE=${PHONE:-gabriel@172.16.42.1}
SSH=(ssh -i "$HOME/.ssh/op8_pmos" -o HostKeyAlias=172.16.42.1 -o ConnectTimeout=10 "$PHONE")
STAGE=armdeck-staging/deploy

entries() { grep -v -E '^[[:space:]]*(#|$)' "$MANIFEST"; }
lhash() { sed 's/\r$//' "$1" | sha256sum | cut -c1-16; }

# prints "target hash" for every entry; the hash is "missing" or "root-only" when it cannot be read
remote_hashes() {
	entries | awk '{print $1, $3}' | "${SSH[@]}" '
		h() { sed "s/\r\$//" | sha256sum | cut -c1-16; }
		while read -r where target; do
			if [ "$where" = container ]; then
				if podman exec steam test -e "$target" < /dev/null 2>/dev/null; then
					r=$(podman exec steam cat "$target" < /dev/null | h)
				else
					r=missing
				fi
			elif [ ! -x "$(dirname "$target")" ] || { [ -e "$target" ] && [ ! -r "$target" ]; }; then
				r=root-only
			elif [ -e "$target" ]; then
				r=$(h < "$target")
			else
				r=missing
			fi
			echo "$target $r"
		done'
}

compare() {   # prints "status where source target mode [replaces]"
	declare -A rh
	while read -r t h; do rh[$t]=$h; done < <(remote_hashes)
	while read -r where src target mode old; do
		[ -f "$U/$src" ] || { echo "NO-SOURCE $where $src $target $mode $old"; continue; }
		r=${rh[$target]:-unknown}
		case $r in
			missing|root-only|unknown) st=$r ;;
			*) [ "$r" = "$(lhash "$U/$src")" ] && st=same || st=DIFFERENT ;;
		esac
		echo "$st $where $src $target $mode $old"
	done < <(entries)
}

case "${1:-check}" in
check)
	compare | awk '{printf "%-10s %-10s %s\n", $1, $2, $4}'
	;;
stage)
	T=$(mktemp -d)
	mkdir -p "$T/files"
	n=0
	{
		echo '#!/bin/sh'
		echo "# Generated by tools/deploy.sh on $(date '+%F %T') from commit $(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null)$(git -C "$ROOT" diff --quiet -- userspace 2>/dev/null || echo ' + uncommitted changes')."
		cat <<'EOF'
# Run on the phone as the normal user: sh ~/armdeck-staging/deploy/install.sh
set -u
D=$(cd "$(dirname "$0")" && pwd)
B=$D/backup-$(date +%Y%m%d-%H%M%S)
changed=""
put() {   # where file target mode [old name]
	w=$1; s=$D/files/$2; t=$3; m=$4; o=${5:-}
	if [ "$w" = container ]; then
		podman cp "$s" steam:/tmp/armdeck-deploy.tmp || { echo "FAILED     $t (container not running?)"; return; }
		if podman exec -u root steam cmp -s /tmp/armdeck-deploy.tmp "$t"; then echo "same       $t (container)"; return; fi
		mkdir -p "$B/container$(dirname "$t")"
		podman exec steam cat "$t" > "$B/container$t" 2>/dev/null
		podman exec -u root steam install -D -m "$m" /tmp/armdeck-deploy.tmp "$t" && echo "installed  $t (container)"
		changed="$changed $t"
		return
	fi
	S=; [ "$w" = host-root ] && S=sudo
	if $S cmp -s "$s" "$t" 2>/dev/null; then
		echo "same       $t"
	else
		if $S test -e "$t"; then mkdir -p "$B$(dirname "$t")"; $S cp -p "$t" "$B$t"; fi
		$S mkdir -p "$(dirname "$t")"
		$S install -m "$m" "$s" "$t" && echo "installed  $t"
		changed="$changed $t"
	fi
	if [ -n "$o" ] && $S test -e "$o"; then
		mkdir -p "$B$(dirname "$o")"
		$S mv "$o" "$B$o" && echo "moved away $o (older name, kept in the backup)"
		changed="$changed $o"
	fi
}
EOF
		while read -r st where src target mode old; do
			[ "$st" = same ] && continue
			[ "$st" = NO-SOURCE ] && { echo "echo 'skipped $target: $src is not in the repository'"; continue; }
			n=$((n + 1))
			f=$(printf '%02d-%s' "$n" "$(basename "$src")")
			sed 's/\r$//' "$U/$src" > "$T/files/$f"
			echo "put $where $f $target $mode $old"
		done < <(compare)
		cat <<'EOF'
case "$changed" in *" /etc/systemd/system/"*) sudo systemctl daemon-reload ;; esac
case "$changed" in *"/.config/systemd/user/"*) systemctl --user daemon-reload ;; esac
case "$changed" in *" /etc/udev/rules.d/"*) sudo udevadm control --reload && echo "udev rules reloaded" ;; esac
case "$changed" in *journald.conf.d*) sudo systemctl restart systemd-journald && echo "journald restarted" ;; esac
for s in op8-thermal op8-sampler op8-tune; do
	case "$changed" in *"/$s "*|*"/$s.service"*|*"/$s") sudo systemctl try-restart "$s.service" && echo "$s restarted" ;; esac
done
case "$changed" in *op8-powerbtn*) systemctl --user try-restart op8-powerbtn.service && echo "op8-powerbtn restarted" ;; esac
case "$changed" in *steam-*|*op8-fpslimit*|*op8-mangoapp*|*op8-touchmode*|*op8-buttons*|*MangoHud*|*dbus-send*|*steamos-*)
	echo "The Steam session uses its new files from its next start: systemctl --user restart steam-gs" ;; esac
case "$changed" in *pipewire*|*wireplumber*)
	echo "Audio files changed: they apply after a reboot (restarting PipeWire leaves Steam without sound)" ;; esac
case "$changed" in *polkit-1*) echo "polkit rules now:"; sudo ls -l /etc/polkit-1/rules.d/ ;; esac
[ -d "$B" ] && echo "Backups of the replaced files: $B"
echo "== done"
EOF
	} > "$T/install.sh"
	if [ "$n" = 0 ]; then echo "Nothing to stage: the phone matches the repository."; rm -rf "$T"; exit 0; fi
	"${SSH[@]}" "rm -rf ~/$STAGE.new && mkdir -p ~/$STAGE.new" || exit 1
	scp -q -r -i "$HOME/.ssh/op8_pmos" -o HostKeyAlias=172.16.42.1 "$T/files" "$T/install.sh" "$PHONE:$STAGE.new/" || exit 1
	"${SSH[@]}" "rm -rf ~/$STAGE.files.old; [ -d ~/$STAGE/files ] && mv ~/$STAGE/files ~/$STAGE.files.old; mkdir -p ~/$STAGE && mv ~/$STAGE.new/files ~/$STAGE.new/install.sh ~/$STAGE/ && rmdir ~/$STAGE.new && rm -rf ~/$STAGE.files.old && sh -n ~/$STAGE/install.sh && echo staged"
	echo "$n file(s) staged. On the phone: sh ~/$STAGE/install.sh"
	grep '^put ' "$T/install.sh" | awk '{print "  " $4}'
	rm -rf "$T"
	;;
*)
	sed -n '2,13p' "$0"; exit 2 ;;
esac
